### ISSUE TITLE
Using CentOS

### ISSUE THREAD

**Issue by eeid26** [jppop/dctm-docker#1]
First Excellent work.

Are using CentOS to do your work? What version?
I would like to try to use your scripts to deploy parts of xcp.

**Comment by jppop** [comment]
Thank you.

The content server, connection broker images are based on a CentOS 6 image (https://registry.hub.docker.com/u/library/centos/).
Oracle XE server image based on a debian distrib.
The tomcat-based images (bam, bps, apphost, xms, ...) are based on official tomcat 7 images (https://registry.hub.docker.com/_/tomcat/ which should be based on a debian distrib).
