### ISSUE TITLE
dctm-docker/dctm-catalog/install.sh

### ISSUE THREAD

**Issue by eeid26** [jppop/dctm-docker#2]
the script in dctm-docker/dctm-catalog/install.sh
is referencing 

``` html
$SOURCE/oracle/11.2/*.*
```

as

``` html
cp $SOURCE/oracle/11.2/*.* $TARGET/dctm-cs/bundles/
```

Is this correct?
What should I have in this directory?
Thank you

**Comment by jppop** [comment]
The directory must content the oracle client (oracle-instantclient11.2-basic-11.2.0.4.0-1.x86_64.rpm, oracle-instantclient11.2-devel-11.2.0.4.0-1.x86_64.rpm and oracle-instantclient11.2-sqlplus-11.2.0.4.0-1.x86_64.rpm).

I have added a screen shot of the missing part of the "catalog" (https://github.com/jppop/dctm-docker/tree/master/dctm-catalog).
